---
# tasks file for download ocp files
- name: Delete OCP4 files, if requested, to download again
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "/usr/local/src/openshift-client-linux.tar.gz"
    - "/usr/local/src/openshift-install-linux.tar.gz"
    - "/usr/local/src/rhcos-live-ppc64le.iso"
    - "/var/www/html/install/rootfs.img"
    - "/var/lib/tftpboot/rhcos/initramfs.img"
    - "/var/lib/tftpboot/rhcos/kernel"
  when: force_ocp_download or install_type == "sno" or install_type == "normal" or (install_type == "assisted" and assisted_iso_type != "full-iso")

- name: Preparing OCP client
  when: ocp_client is defined
  block:
    - name: "Downloading OCP4 client"
      get_url:
        url: "{{ ocp_client }}"
        dest: /usr/local/src/openshift-client-linux.tar.gz
        force: true

    - name: Unarchiving OCP4 client
      unarchive:
        src: /usr/local/src/openshift-client-linux.tar.gz
        dest: /usr/local/bin
        remote_src: yes

- name: Preparing OCP installer
  when: ocp_installer is defined
  block:
    - name: "Downloading OCP4 Installer"
      get_url:
        url: "{{ ocp_installer }}"
        dest: /usr/local/src/openshift-install-linux.tar.gz
        force: true

    - name: Unarchiving OCP4 Installer
      unarchive:
        src: /usr/local/src/openshift-install-linux.tar.gz
        dest: /usr/local/bin
        remote_src: yes

- name: Removing files that are not needed
  file:
    path: /usr/local/bin/README.md
    state: absent

- name: Download CoreOS images for RHCOS-10
  include_tasks: download_coreos_files_rhcos10.yaml
  when: "os_image_stream is not defined or os_image_stream == '' or os_image_stream == 'rhel-10'"

- name: Download CoreOS images for RHCOS-9
  include_tasks: download_coreos_files_rhcos9.yaml
  when: "os_image_stream is defined and os_image_stream == 'rhel-9'"
